
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Fri Dec 13 20:32:46 CST 2013
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int STRLIT = 11;
  static final int rw_WHILE = 35;
  static final int rw_BOOL = 40;
  static final int LBRACKET = 13;
  static final int INCREMENT = 29;
  static final int rw_IF = 34;
  static final int SLASH = 25;
  static final int rw_CONTINUE = 44;
  static final int rw_FALSE = 46;
  static final int LPAREN = 4;
  static final int SEMI = 3;
  static final int rw_PRINT = 41;
  static final int rw_TRUE = 45;
  static final int MINUS = 28;
  static final int DECREMENT = 30;
  static final int RPAREN = 5;
  static final int NOT = 26;
  static final int INTLIT = 10;
  static final int rw_VOID = 31;
  static final int LT = 17;
  static final int rw_CONST = 33;
  static final int COMMA = 6;
  static final int rw_ELSE = 36;
  static final int GEQ = 22;
  static final int PLUS = 27;
  static final int rw_READ = 37;
  static final int rw_INT = 38;
  static final int EOF = 0;
  static final int RBRACKET = 14;
  static final int error = 1;
  static final int COR = 16;
  static final int rw_CLASS = 32;
  static final int rw_RETURN = 42;
  static final int EQ = 19;
  static final int ASG = 7;
  static final int TIMES = 23;
  static final int CHARLIT = 12;
  static final int COLON = 24;
  static final int LBRACE = 8;
  static final int rw_CHAR = 39;
  static final int RBRACE = 9;
  static final int CAND = 15;
  static final int LEQ = 21;
  static final int rw_BREAK = 43;
  static final int GT = 18;
  static final int NOTEQ = 20;
  static final int IDENTIFIER = 2;
}

